#cloud-config
repo_update: true
repo_upgrade: all
package_upgrade: true
packages:
- NetworkManager

cloud_config_modules:
- runcmd
- package_update_upgrade_install

runcmd:
- [ systemctl, daemon-reload ]
- [ systemctl, enable, NetworkManager.service ]
- [ systemctl, start, --no-block, NetworkManager.service ]

users:
- default

system_info:
  default_user:
    name: ec2-user
